### ISSUE TITLE
Change the value of spark.eventLog.dir?

### ISSUE THREAD

**Issue by ghost** [cjonesy/docker-spark#12]
In the [config file](https://github.com/cjonesy/docker-spark/blob/359cb090dd0b94c497f89517733d2a15e71db40a/spark-defaults.conf), **spark.eventLog.dir** is set to file:///tmp/spark-events.

The Spark [official document](https://spark.apache.org/docs/latest/configuration.html) recommends to set **spark.eventLog.dir** to a unified location instead of tmp.
"Users may want to set this to a unified location like an HDFS directory so history files can be read by the history server.""

I wonder if the value of this parameter need to be changed. Thanks.

**Comment by cjonesy** [comment]
I kept the defaults in the `spark-defaults.conf` file (although it was probably is old), but I do have an environment variable you can set to change the path here: https://github.com/cjonesy/docker-spark/blob/3c6051fc3c33dbe4c4373431a5257a22ad0514f4/entrypoint.sh#L57

Launching with the log path would look something like this: `docker run -e SPARK_EVENTLOG_ENABLED=true -e SPARK_EVENTLOG_DIR=file:///foo/bar -it cjonesy/docker-spark spark-shell`
